name: CI/CD for Django on Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  source:
    name: Source Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  build:
    name: Build Stage
    runs-on: ubuntu-latest
    needs: source
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pylint

      - name: Run Pylint
        run: |
          ls
          pylint --disable=R,C,W .py **/.py